# Generated by Django 3.0.5 on 2020-05-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200503_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='published at'),
        ),
    ]
